hmmconfsite/demo/urls.py
from django.urls import path, re_path, register_converter
from . import views


app_name = 'demo'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('upload_data', views.UploadDataView.as_view(), name='upload_data'),
    path('ajax/get_barplot_case', views.get_barplot_case, name='get_barplot_case'),
    path('event_stream/<int:event_id>', views.json_event_stream_data, name='json_event_stream'),
    path('ajax/replay_previous_event', views.replay_previous_event, name='replay_previous_event'),
    path('ajax/replay_next_event', views.replay_next_event, name='replay_next_event'),
    path('ajax/retrieve_record', views.retrieve_record, name='retrieve_record'),
    path('ajax/state_transition', views.state_transition, name='state_transition'),
    path('ajax/observation_update', views.observation_update, name='observation_update'),
    path('json_conformance_data/<int:event_id>', views.json_conformance_data, name='json_conformance'),
    path('ajax/compute_conformance', views.compute_conformance, name='compute_conformance'),
]

hmmconfsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('hmmconfsite.demo.urls')),
    path('admin/', admin.site.urls),
]

hmmconfsite/demo/forms.py
from django import forms


from . import models


def validate_filename_extension(filename, *exts):
    cond = False
    for ext in exts:
        cond = cond or filename.endswith(ext)
    if not cond:
        s = ' or '.join(exts)
        err_msg = 'File extension should be {}'.format(s)
        raise forms.ValidationError(err_msg)


def validate_file_pnml(file_):
    validate_filename_extension(file_.name, '.pnml', '.apnml')


def validate_file_npy(file_):
    validate_filename_extension(file_.name, '.npy')


def validate_file_csv(file_):
    validate_filename_extension(file_.name, '.csv')


class UploadDataForm(forms.Form):
    file_pnml = forms.FileField(validators=[validate_file_pnml])
    file_logstartprob = forms.FileField(validators=[validate_file_npy])
    file_logtranscube = forms.FileField(validators=[validate_file_npy])
    file_logtranscube_d = forms.FileField(validators=[validate_file_npy])
    file_logemitmat = forms.FileField(validators=[validate_file_npy])
    file_logemitmat_d = forms.FileField(validators=[validate_file_npy])
    file_confmat = forms.FileField(validators=[validate_file_npy])
    file_state_csv = forms.FileField(validators=[validate_file_csv])
    file_event_csv = forms.FileField(validators=[validate_file_csv])


class CaseChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        str_ = '{:<8} - {}'
        is_train = 'train' if obj.is_train else 'test'
        str_ = str_.format(obj.caseid, is_train)
        return str_


class CaseChoiceSelectForm(forms.Form):
    case_select = CaseChoiceField(queryset=None, label='Replay case')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        first_events = models.Event.objects.filter(index__exact=0).order_by('id')
        self.fields['case_select'].queryset = first_events

hmmconfsite/demo/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.http import JsonResponse, Http404

from . import forms, models
from .utils import make_logger


logger = make_logger('views.py')


def index(request):
    log = models.Log.objects.first()

    # there is no data, so make the user upload something
    if log is None:
        return UploadDataView.as_view()(request)

    if request.method == 'POST':
        case_select_form = forms.CaseChoiceSelectForm(request.POST)

        if case_select_form.is_valid():
            event = case_select_form.cleaned_data['case_select']
            event_id = event.id
        else:
            raise Http404('Case ID not found.')
    else:
        # try to get caseid and event
        caseid = request.GET.get('caseid', None)

        if caseid is None:
            event = models.Event.objects.filter(index__exact=0).first()
            event_id = event.id
        else:
            event_id = request.GET.get('event_id')
            event = models.Event.objects.filter(
                caseid__exact=event.caseid,
                index__exact=0,
            ).first()

        initial = {
            'case_select': event
        }
        case_select_form = forms.CaseChoiceSelectForm(initial=initial)

    context = {
        'log_id': log.id,
        'case_select_form': case_select_form,
        'caseid': event.caseid,
        'event_id': event_id,
    }

    return render(request, 'demo/index.html', context)


def about(request):
    context = {

    }
    return render(request, 'demo/about.html', context)


def replay_previous_event(request):
    event_id = request.GET.get('event_id', -1)
    event = models.Event.objects.get(pk=event_id)
    assert isinstance(event, models.Event)

    caseid = event.caseid
    prev_event = models.Event.objects.filter(
        caseid__exact=caseid,
        index__exact=event.index - 1,
    ).order_by('index').first()

    # if there is no next event, just use the current event
    if not prev_event:
        prev_event = event

    # need to update case event table data
    case_events = models.Event.objects.filter(
        caseid__exact=caseid
    ).order_by('index')

    rows = []
    for event_i in case_events:
        row = {
            # so that it's not 0-index
            'index': event_i.index + 1,
            'activity_label': event_i.activity,
            'current': event_i.id == prev_event.id,
        }
        rows.append(row)

    data = {
        'event_id': prev_event.id,
        'case_events': rows,
    }

    return JsonResponse(data)


def replay_next_event(request):
    event_id = request.GET.get('event_id', -1)
    event = models.Event.objects.get(pk=event_id)
    assert isinstance(event, models.Event)

    caseid = event.caseid
    next_event = models.Event.objects.filter(
        caseid__exact=caseid,
        index__exact=event.index + 1,
    ).order_by('index').first()

    # if there is no next event, just use the current event
    if not next_event:
        next_event = event

    # need to update case event table data
    case_events = models.Event.objects.filter(
        caseid__exact=caseid
    ).order_by('index')

    rows = []
    for event_i in case_events:
        row = {
            # so that it's not 0-index
            'index': event_i.index + 1,
            'activity_label': event_i.activity,
            'current': event_i.id == next_event.id,
        }
        rows.append(row)

    data = {
        'event_id': next_event.id,
        'case_events': rows,
    }

    return JsonResponse(data)


def json_event_stream_data(request, event_id):
    event = models.Event.objects.get(pk=event_id)
    caseid = event.caseid
    case_events = models.Event.objects.filter(
        caseid__exact=caseid
    ).order_by('index')

    rows = []
    for event_i in case_events:
        row = {
            # so that it's not 0-index
            'index': event_i.index + 1,
            'activity_label': event_i.activity,
            'current': event_i.id == event.id
        }
        rows.append(row)

    data = {
        'rows': rows
    }

    return JsonResponse(data)


def get_barplot_case(request):
    log_id = request.GET.get('log_id', -1)

    log = models.Log.objects.get(pk=log_id)
    assert isinstance(log, models.Log)

    case_length_file = log.get_barplot_case_length()
    unique_activity_file = log.get_barplot_case_unique_activity()

    data = {
        'barplot_case_length_url': case_length_file.url,
        'barplot_case_length_name': case_length_file.name,
        'barplot_case_unique_activity_url': unique_activity_file.url,
        'barplot_case_unique_activity_name': unique_activity_file.name,
    }
    return JsonResponse(data)


class UploadDataView(FormView):
    template_name = 'demo/upload_data.html'
    form_class = forms.UploadDataForm
    success_url = '/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        assert isinstance(form, forms.UploadDataForm)

        file_pnml = form.cleaned_data['file_pnml']
        file_logstartprob = form.cleaned_data['file_logstartprob']
        file_logtranscube = form.cleaned_data['file_logtranscube']
        file_logtranscube_d = form.cleaned_data['file_logtranscube_d']
        file_logemitmat = form.cleaned_data['file_logemitmat']
        file_logemitmat_d = form.cleaned_data['file_logemitmat_d']
        file_confmat = form.cleaned_data['file_confmat']
        file_state_csv = form.cleaned_data['file_state_csv']
        file_event_csv = form.cleaned_data['file_event_csv']

        models.create_objects(
            file_pnml, file_logstartprob,
            file_logtranscube, file_logtranscube_d,
            file_logemitmat, file_logemitmat_d,
            file_confmat, file_state_csv,
            file_event_csv, row_limit=10000
        )

        return super().form_valid(form)


def retrieve_record(request):
    event_id = request.GET.get('event_id', -1)
    event = models.Event.objects.get(pk=event_id)
    log = models.Log.objects.first()
    assert isinstance(event, models.Event)

    # get previous state estimation or initial estimation
    if event.index == 0:
        # get initial estimation
        file_barplot_state = log.get_file_barplot_logstartprob()
        file_net_state = log.get_file_net_logstartprob()
    else:
        # the previous event's final state estimation
        prev_event = models.Event.objects.filter(
            index__exact=event.index - 1,
            caseid__exact=event.caseid
        ).first()
        assert isinstance(prev_event, models.Event)
        file_barplot_state = prev_event.get_file_barplot_logfwd()
        file_net_state = prev_event.get_file_net_logfwd()

    data = {
        'event_id': event_id,
        'barplot_state_url': file_barplot_state.url,
        'barplot_state_name': file_barplot_state.name,
        'net_state_url': file_net_state.url,
        'net_state_name': file_net_state.name,
    }

    return JsonResponse(data)


def state_transition(request):
    event_id = request.GET.get('event_id', -1)
    event = models.Event.objects.get(pk=event_id)
    assert isinstance(event, models.Event)

    # just return the current estimation if it's the first event
    # otherwise do the state transition
    if event.index == 0:
        return retrieve_record(request)
    else:
        file_barplot_state = event.get_file_barplot_logfwd_before_obs()
        file_net_state = event.get_file_net_logfwd_before_obs()

        data = {
            'event_id': event_id,
            'barplot_state_url': file_barplot_state.url,
            'barplot_state_name': file_barplot_state.name,
            'net_state_url': file_net_state.url,
            'net_state_name': file_net_state.name,
        }

        return JsonResponse(data)


def observation_update(request):
    event_id = request.GET.get('event_id', -1)
    event = models.Event.objects.get(pk=event_id)
    assert isinstance(event, models.Event)

    file_barplot_state = event.get_file_barplot_logfwd()
    file_net_state = event.get_file_net_logfwd()

    data = {
        'event_id': event_id,
        'barplot_state_url': file_barplot_state.url,
        'barplot_state_name': file_barplot_state.name,
        'net_state_url': file_net_state.url,
        'net_state_name': file_net_state.name,
    }

    return JsonResponse(data)


def get_conformance_data(event_id):
    event = models.Event.objects.get(pk=event_id)
    assert isinstance(event, models.Event)

    if event.index == 0:
        prev_event_str = '-'
    else:
        prev_event = models.Event.objects.filter(
            index__exact=event.index - 1,
            caseid__exact=event.caseid,
        ).first()
        prev_event_str = prev_event.activity

    case_events = models.Event.objects.filter(
        caseid__exact=event.caseid,
        log__exact=event.log,
        index__lte=event.index,
    )

    # compute total injected distance
    total_injected_distance = case_events.values_list('injected_distance', flat=True)
    total_injected_distance = sum(total_injected_distance)

    # compute avg. conformance
    avgconf = list(case_events.values_list('finalconf', flat=True))
    avgconf = sum(avgconf) / len(avgconf)

    # conformance table data
    row_caseid = {
        'attribute': 'Case ID',
        'value': event.caseid
    }
    row_prev_event = {
        'attribute': 'Previous event',
        'value': prev_event_str,
    }
    row_event = {
        'attribute': 'Current event',
        'value': event.activity,
    }
    row_finalconf = {
        'attribute': 'Final conformance',
        'value': '{:.5f}'.format(event.finalconf),
    }
    row_injected_distance = {
        'attribute': 'Injected distance',
        'value': '{:.5f}'.format(event.injected_distance),
    }
    row_total_injected_distance = {
        'attribute': 'Total injected distance',
        'value': '{:.5f}'.format(total_injected_distance),
    }

hmmconfsite/demo/templates/demo/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1 class="mt-5">About HMMConf</h1>
<h3 class="text-muted">An online conformance checking based on Hidden Markov Models (HMM)</h3>
<p>
This is a demo of the online conformance checking technique (HMMConf). The technique is based on 
Hidden Markov Models (HMM) and performs conformance checking by alternating between orienting the 
running case within the process and conformance computation. This tackles the challenge of balancing
between making sense at the process level as the case reaches completion and putting emphasis on 
the current information at the same time.
</p>
<p>
The demo illustrates how the technique would work at an online scenario where events related to 
different cases are coming and conformance is being computed as they come in. The dataset is a 
real-life dataset of a <a href="https://doi.org/10.4121/uuid:76c46b83-c930-4798-a1c9-4be94dfeb741">hospital billing process</a>.
</p>
<p>
For more detail and the implementation, please check out the <a href="https://github.com/jwllee/HMMConf">Github repository</a>.
</p>
{% endblock %}

hmmconfsite/demo/templates/demo/index.html
{% extends 'base.html' %}
{% load static %}
{% block nav-buttons %}
<button class="btn btn-outline-success ml-auto mr-1"
    type="button" data-toggle="collapse" data-target="#barplot"
    aria-expanded="false" aria-controls="barplot">Case distribution plots</button>
{% endblock %}

{% load crispy_forms_tags %}
{% load thumbnail %}

{% block content %}
<div class="card collapse p-3 mt-5" 
    id="barplot" 
    data-log-id={{ log_id }}
    data-get-barplot-url="{% url 'demo:get_barplot_case' %}">
    <div class="card-body">
        <h5 class="card-title">Case distribution plots</div>
        <div class="row-sm" id="barplot_case_length"></div>
        <div class="row-sm" id="barplot_unique_activity"></div>
    </div>
</div>
<div class="row justify-content-md-center">
    <div class="col-4 col-md-3">
        <div class="sticky-top">
            <h5 class="card-title">Choose case to replay:</h5>
            <hr class="mt-0 mb-4">
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ case_select_form | crispy }}
                <button class="btn btn-primary" type="submit">Update</button>
            </form>
            <h5 class="card-title mt-5">Case events:</h5>
            <table
                id="table-event"
                class="table-borderless table-sm"
                data-toggle="table"
                data-height="250"
                data-url="{% url 'demo:json_event_stream' event_id %}"
                data-row-style='RowStyle'>
                <thead>
                    <tr>
                        <th data-field='index'>Event index</th>
                        <th data-field='activity_label'>Activity</th>
                        <th data-field='current' data-visible="false"></th>
                    </tr>
                </thead>
            </table>
            <div class="button-group">
                <button
                    class="btn btn-primary mt-3" 
                    id="previous_event"
                    onclick="replay_previous_event()">
                    Previous event
                </button>
                <button 
                    class="btn btn-primary mt-3" 
                    id="next_event"
                    onclick="replay_next_event()">
                    Next event
                </button>
            </div>
        </div>
    </div>
    <div 
        class="col-8 col-md-9" 
        id="replay_detail" 
        data-event-id="{{ event_id }}"
        data-replay-previous-event-url="{% url 'demo:replay_previous_event' %}"
        data-replay-next-event-url="{% url 'demo:replay_next_event' %}">
        <div 
            class="card mb-3 p-2"
            id="retrieve-record"
            data-retrieve-record-url="{% url 'demo:retrieve_record' %}">
            <div class="row no-gutters">
                <div class="col-md-4 d-flex flex-wrap align-items-center">
                    <img 
                        class="img-fluid" 
                        id="barplot-start-state" 
                        alt="State estimation"/>
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">1. Retrieve record</h5>
                        <h6 class="card-subtitle mb-3 text-muted">
                            When a new event comes in, the last state estimation of the corresponding case is retrieved. If the 
                            new event is the first observed event of the case, then the initial state estimation of the process is used.
                        </h6>
                        <div class="row justify-content-md-center">
                            <img 
                                class="img-fluid" 
                                style="max-height: 250px;"
                                id="net-start-state" 
                                alt="Model highlighted with mode state estimation"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div 
            class="card mb-3"
            id="state-transition"
            data-state-transition-url="{% url 'demo:state_transition' %}">
            <div class="row no-gutters">
                <div class="col-md-4 d-flex flex-wrap align-items-center">
                    <img 
                        class="img-fluid" 
                        id="barplot-transition-state" 
                        alt="State estimation after state transition from previous event"/>
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">2. State transition</h5>
                        <h6 class="card-subtitle mb-2 text-muted">
                            If there is a previous event, then we need to account for the state-transition probability from each state
                            of the previous state estimation. Otherwise, no changes are made to the state estimation from the previous step.
                        </h6>
                        <div class="row justify-content-md-center">
                            <img 
                                class="img-fluid" 
                                style="max-height: 250px;"
                                id="net-transition-state" 
                                alt="Model highlighted with mode state estimation after state transition from previous event"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div 
            class="card mb-3"
            id="observation-update"
            data-observation-update-url="{% url 'demo:observation_update' %}">
            <div class="row no-gutters">
                <div class="col-md-4 d-flex flex-wrap align-items-center">
                    <img 
                        class="img-fluid" 
                        id="barplot-observation-state" 
                        alt="State estimation after update with current event"/>
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">3. Observation update</h5>
                        <h6 class="card-subtitle mb-2 text-muted">
                            The information from the current observed event is incorporated into the current state estimation.
                        </h6>
                        <div class="row justify-content-md-center">
                            <img 
                                class="img-fluid" 
                                style="max-height: 250px;"
                                id="net-observation-state" 
                                alt="Model highlighted with mode state estimation after update with current event"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div 
            class="card mb-3"
            id="compute-conformance"
            data-compute-conformance-url="{% url 'demo:compute_conformance' %}">
            <div class="row no-gutters">
                <div class="col-md-4 d-flex flex-wrap align-items-center">
                    <img 
                        class="img-fluid"
                        id="barplot-final-state"
                        alt="Final state estimation"/>
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <div class="row pl-3">
                            <div class="col">
                        <h5 class="card-title">4. Conformance computation</h5>
                        <p class="card-text">
                            Having computed the final state estimation, conformance of the current event is computed with
                            respect to the current state estimation. 
                        </p>
                        <p class="card-text"> 
                            Various other conformance metrics are also computed, 
                            e.g., injected distance, and completeness.
                        </p>
                            </div>
                            <div class="col">
                            <table
                                id="table-conformance"
                                class="table-sm"
                                data-toggle="table"
                                data-url="{% url 'demo:json_conformance' event_id %}"
                                data-row-style='RowStyle'>
                                <thead>
                                    <tr>
                                        <th 
                                            data-field='attribute'
                                            data-width='200'>Attribute</th>
                                        <th 
                                            data-field='value'
                                            data-width='150'>Value</th>
                                    </tr>
                                </thead>
                            </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
    <script type='text/javascript' src="{% static 'js/get_case_plots.js' %}"></script>
    <script>
        function RowStyle(row, index) {
            if (row.current) {
                return {
                    css: {
                        'background-color': '#99ff33',
                    }
                };
            }
            else {
                return {};
            }
        }
    </script>
    <!--Script to replay next event-->
    <script type='text/javascript' src="{% static 'js/replay_event.js' %}"></script>
{% endblock %}

hmmconfsite/demo/templates/demo/upload_data.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>
{% endblock %}