hmmconfsite/demo/urls.py
from django.urls import path, re_path, register_converter
from . import views


app_name = 'demo'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('upload_data', views.UploadDataView.as_view(), name='upload_data'),
    path('ajax/get_barplot_case', views.get_barplot_case, name='get_barplot_case'),
    path('event_stream/<int:event_id>', views.json_event_stream_data, name='json_event_stream'),
    path('ajax/replay_previous_event', views.replay_previous_event, name='replay_previous_event'),
    path('ajax/replay_next_event', views.replay_next_event, name='replay_next_event'),
    path('ajax/retrieve_record', views.retrieve_record, name='retrieve_record'),
    path('ajax/state_transition', views.state_transition, name='state_transition'),
    path('ajax/observation_update', views.observation_update, name='observation_update'),
    path('json_conformance_data/<int:event_id>', views.json_conformance_data, name='json_conformance'),
    path('ajax/compute_conformance', views.compute_conformance, name='compute_conformance'),
]

hmmconfsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('hmmconfsite.demo.urls')),
    path('admin/', admin.site.urls),
]

hmmconfsite/demo/forms.py
from django import forms


from . import models


def validate_filename_extension(filename, *exts):
    cond = False
    for ext in exts:
        cond = cond or filename.endswith(ext)
    if not cond:
        s = ' or '.join(exts)
        err_msg = 'File extension should be {}'.format(s)
        raise forms.ValidationError(err_msg)


def validate_file_pnml(file_):
    validate_filename_extension(file_.name, '.pnml', '.apnml')


def validate_file_npy(file_):
    validate_filename_extension(file_.name, '.npy')


def validate_file_csv(file_):
    validate_filename_extension(file_.name, '.csv')


class UploadDataForm(forms.Form):
    file_pnml = forms.FileField(validators=[validate_file_pnml])
    file_logstartprob = forms.FileField(validators=[validate_file_npy])
    file_logtranscube = forms.FileField(validators=[validate_file_npy])
    file_logtranscube_d = forms.FileField(validators=[validate_file_npy])
    file_logemitmat = forms.FileField(validators=[validate_file_npy])
    file_logemitmat_d = forms.FileField(validators=[validate_file_npy])
    file_confmat = forms.FileField(validators=[validate_file_npy])
    file_state_csv = forms.FileField(validators=[validate_file_csv])
    file_event_csv = forms.FileField(validators=[validate_file_csv])


class CaseChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        str_ = '{:<8} - {}'
        is_train = 'train' if obj.is_train else 'test'
        str_ = str_.format(obj.caseid, is_train)
        return str_


class CaseChoiceSelectForm(forms.Form):
    case_select = CaseChoiceField(queryset=None, label='Replay case')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        first_events = models.Event.objects.filter(index__exact=0).order_by('id')
        self.fields['case_select'].queryset = first_events

hmmconfsite/demo/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.http import JsonResponse, Http404

from . import forms, models
from .utils import make_logger


logger = make_logger('views.py')


def index(request):
    log = models.Log.objects.first()

    # there is no data, so make the user upload something
    if log is None:
        return UploadDataView.as_view()(request)

    if request.method == 'POST':
        case_select_form = forms.CaseChoiceSelectForm(request.POST)

        if case_select_form.is_valid():
            event = case_select_form.cleaned_data['case_select']
            event_id = event.id
        else:
            raise Http404('Case ID not found.')
    else:
        # try to get caseid and event
        caseid = request.GET.get('caseid', None)

        if caseid is None:
            event = models.Event.objects.filter(index__exact=0).first()
            event_id = event.id
        else:
            event_id = request.GET.get('event_id')
            event = models.Event.objects.filter(
                caseid__exact=event.caseid,
                index__exact=0,
            ).first()

        initial = {
            'case_select': event
        }
        case_select_form = forms.CaseChoiceSelectForm(initial=initial)

    context = {
        'log_id': log.id,
        'case_select_form': case_select_form,
        'caseid': event.caseid,
        'event_id': event_id,
    }

    return render(request, 'demo/index.html', context)


def about(request):
    context = {

    }
    return render(request, 'demo/about.html', context)


def replay_previous_event(request):
    event_id = request.GET.get('event_id', -1)
    event = models.Event.objects.get(pk=event_id)
    assert isinstance(event, models.Event)

    caseid = event.caseid
    prev_event = models.Event.objects.filter(
        caseid__exact=caseid,
        index__exact=event.index - 1,
    ).order_by('index').first()

    # if there is no next event, just use the current event
    if not prev_event:
        prev_event = event

    # need to update case event table data
    case_events = models.Event.objects.filter(
        caseid__exact=caseid
    ).order_by('index')

    rows = []
    for event_i in case_events:
        row = {
            # so that it's not 0-index
            'index': event_i.index + 1,
            'activity_label': event_i.activity,
            'current': event_i.id == prev_event.id,
        }
        rows.append(row)

    data = {
        'event_id': prev_event.id,
        'case_events': rows,
    }

    return JsonResponse(data)


def replay_next_event(request):
    event_id = request.GET.get('event_id', -1)
    event = models.Event.objects.get(pk=event_id)
    assert isinstance(event, models.Event)

    caseid = event.caseid
    next_event = models.Event.objects.filter(
        caseid__exact=caseid,
        index__exact=event.index + 1,
    ).order_by('index').first()

    # if there is no next event, just use the current event
    if not next_event:
        next_event = event

    # need to update case event table data
    case_events = models.Event.objects.filter(
        caseid__exact=caseid
    ).order_by('index')

    rows = []
    for event_i in case_events:
        row = {
            # so that it's not 0-index
            'index': event_i.index + 1,
            'activity_label': event_i.activity,
            'current': event_i.id == next_event.id,
        }
        rows.append(row)

    data = {
        'event_id': next_event.id,
        'case_events': rows,
    }

    return JsonResponse(data)


def json_event_stream_data(request, event_id):
    event = models.Event.objects.get(pk=event_id)
    caseid = event.caseid
    case_events = models.Event.objects.filter(
        caseid__exact=caseid
    ).order_by('index')

    rows = []
    for event_i in case_events:
        row = {
            # so that it's not 0-index
            'index': event_i.index + 1,
            'activity_label': event_i.activity,
            'current': event_i.id == event.id
        }
        rows.append(row)

    data = {
        'rows': rows
    }

    return JsonResponse(data)


def get_barplot_case(request):
    log_id = request.GET.get('log_id', -1)

    log = models.Log.objects.get(pk=log_id)
    assert isinstance(log, models.Log)

    case_length_file = log.get_barplot_case_length()
    unique_activity_file = log.get_barplot_case_unique_activity()

    data = {
        'barplot_case_length_url': case_length_file.url,
        'barplot_case_length_name': case_length_file.name,
        'barplot_case_unique_activity_url': unique_activity_file.url,
        'barplot_case_unique_activity_name': unique_activity_file.name,
    }
    return JsonResponse(data)


class UploadDataView(FormView):
    template_name = 'demo/upload_data.html'
    form_class = forms.UploadDataForm
    success_url = '/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        assert isinstance(form, forms.UploadDataForm)

        file_pnml = form.cleaned_data['file_pnml']
        file_logstartprob = form.cleaned_data['file_logstartprob']
        file_logtranscube = form.cleaned_data['file_logtranscube']
        file_logtranscube_d = form.cleaned_data['file_logtranscube_d']
        file_logemitmat = form.cleaned_data['file_logemitmat']
        file_logemitmat_d = form.cleaned_data['file_logemitmat_d']
        file_confmat = form.cleaned_data['file_confmat']
        file_state_csv = form.cleaned_data['file_state_csv']
        file_event_csv = form.cleaned_data['file_event_csv']

        models.create_objects(
            file_pnml, file_logstartprob,
            file_logtranscube, file_logtranscube_d,
            file_logemitmat, file_logemitmat_d,
            file_confmat, file_state_csv,
            file_event_csv, row_limit=10000
        )

        return super().form_valid(form)


def retrieve_record(request):
    event_id = request.GET.get('event_id', -1)
    event = models.Event.objects.get(pk=event_id)
    log = models.Log.objects.first()
    assert isinstance(event, models.Event)

    # get previous state estimation or initial estimation
    if event.index == 0:
        # get initial estimation
        file_barplot_state = log.get_file_barplot_logstartprob()
        file_net_state = log.get_file_net_logstartprob()
    else:
        # the previous event's final state estimation
        prev_event = models.Event.objects.filter(
            index__exact=event.index - 1,
            caseid__exact=event.caseid
        ).first()
        assert isinstance(prev_event, models.Event)
        file_barplot_state = prev_event.get_file_barplot_logfwd()
        file_net_state = prev_event.get_file_net_logfwd()

    data = {
        'event_id': event_id,
        'barplot_state_url': file_barplot_state.url,
        'barplot_state_name': file_barplot_state.name,
        'net_state_url': file_net_state.url,
        'net_state_name': file_net_state.name,
    }

    return JsonResponse(data)


def state_transition(request):
    event_id = request.GET.get('event_id', -1)
    event = models.Event.objects.get(pk=event_id)
    assert isinstance(event, models.Event)

    # just return the current estimation if it's the first event
    # otherwise do the state transition
    if event.index == 0:
        return retrieve_record(request)
    else:
        file_barplot_state = event.get_file_barplot_logfwd_before_obs()
        file_net_state = event.get_file_net_logfwd_before_obs()

        data = {
            'event_id': event_id,
            'barplot_state_url': file_barplot_state.url,
            'barplot_state_name': file_barplot_state.name,
            'net_state_url': file_net_state.url,
            'net_state_name': file_net_state.name,
        }

        return JsonResponse(data)


def observation_update(request):
    event_id = request.GET.get('event_id', -1)
    event = models.Event.objects.get(pk=event_id)
    assert isinstance(event, models.Event)

    file_barplot_state = event.get_file_barplot_logfwd()
    file_net_state = event.get_file_net_logfwd()

    data = {
        'event_id': event_id,
        'barplot_state_url': file_barplot_state.url,
        'barplot_state_name': file_barplot_state.name,
        'net_state_url': file_net_state.url,
        'net_state_name': file_net_state.name,
    }

    return JsonResponse(data)


def get_conformance_data(event_id):
    event = models.Event.objects.get(pk=event_id)
    assert isinstance(event, models.Event)

    if event.index == 0:
        prev_event_str = '-'
    else:
        prev_event = models.Event.objects.filter(
            index__exact=event.index - 1,
            caseid__exact=event.caseid,
        ).first()
        prev_event_str = prev_event.activity

    case_events = models.Event.objects.filter(
        caseid__exact=event.caseid,
        log__exact=event.log,
        index__lte=event.index,
    )

    # compute total injected distance
    total_injected_distance = case_events.values_list('injected_distance', flat=True)
    total_injected_distance = sum(total_injected_distance)

    # compute avg. conformance
    avgconf = list(case_events.values_list('finalconf', flat=True))
    avgconf = sum(avgconf) / len(avgconf)

    # conformance table data
    row_caseid = {
        'attribute': 'Case ID',
        'value': event.caseid
    }
    row_prev_event = {
        'attribute': 'Previous event',
        'value': prev_event_str,
    }
    row_event = {
        'attribute': 'Current event',
        'value': event.activity,
    }
    row_finalconf = {
        'attribute': 'Final conformance',
        'value': '{:.5f}'.format(event.finalconf),
    }
    row_injected_distance = {
        'attribute': 'Injected distance',
        'value': '{:.5f}'.format(event.injected_distance),
    }
    row_total_injected_distance = {
        'attribute': 'Total injected distance',
        'value': '{:.5f}'.format(total_injected_distance),
    }

hmmconfsite/demo/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>HMMConf Demo</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
        <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.4/dist/bootstrap-table.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'demo/css/app.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'demo/css/navbar-static-top.css' %}">
        {% block stylesheet %}{% endblock %}
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-152941772-1"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'UA-152941772-1');
        </script>
    </head>
    <body>
        <nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top navbar-static-top justify-content-end">
            <a class="navbar-brand" href="{% url 'demo:index' %}">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" 
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    {% block nav-items %}
                    {% endblock %}
                </ul>
            </div>
            <div class="button-group">
                {% block nav-buttons %}
                {% endblock %}
                <a class="btn btn-outline-secondary ml-auto mr-1"
                    href="{% url 'demo:about' %}">
                    About
                </a>
            </div>
        </nav>
        <main role="main" class="container-fluid">
        <div class="jumbotron p-4">
            <h1>{% block pagetitle %}{% endblock %}</h1>
            {% block content %}{% endblock %}
        </div>
        </main>
        <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://unpkg.com/bootstrap-table@1.15.4/dist/bootstrap-table.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
        <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
        <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
        {% block js %}
        {% endblock %}
    </body>
</html>